# Generated by Django 3.2.18 on 2023-04-25 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230425_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 14, 14, 51, 846934, tzinfo=utc), verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='rise_complaint',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 14, 14, 51, 846934, tzinfo=utc), null=True),
        ),
    ]
