# Generated by Django 3.2.18 on 2023-04-25 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230426_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_detail',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 20, 33, 51, 303029, tzinfo=utc), verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='rise_complaint',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 20, 33, 51, 303029, tzinfo=utc), null=True),
        ),
    ]
