# Generated by Django 4.2 on 2023-05-03 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230426_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 4, 37, 44, 326736, tzinfo=datetime.timezone.utc), verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='rise_complaint',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 4, 37, 44, 325736, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
