# Generated by Django 4.2 on 2023-05-03 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_feedback_date_alter_rise_complaint_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 5, 48, 17, 235949, tzinfo=datetime.timezone.utc), verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='rise_complaint',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 5, 48, 17, 235949, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
