from django.urls import path
from . import views
urlpatterns = [

    path('',views.public_register,name='public_register'),
    path('home/',views.home,name='home'),
    path('public_login/',views.public_login,name='public_login'),
    path('staff_login/',views.staff_login,name='staff_login'),
    path('public_logout/',views.public_logout,name='public_logout'),
    path('public_dashboard/',views.public_dashboard,name='public_dashboard'),
    path('send_query/',views.send_query,name='send_query'),
    path('manage_query/',views.manage_query,name='manage_query'),
    path('water_dashboard/',views.water_dashboard,name='water_dashboard'),
    path('electricity_dashboard/',views.electricity_dashboard,name='electricity_dashboard'),
    path('drain_dashboard/',views.drain_dashboard,name='drain_dashboard'),
    path('road_dashboard/',views.road_dashboard,name='road_dashboard'),
    path('park_dashboard/',views.park_dashboard,name='park_dashboard'),
    path('park_dashboard/',views.park_dashboard,name='park_dashboard'),
    path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('view_complaint/',views.view_complaint,name='view_complaint'),
    path('water_complaint/',views.water_complaint,name='water_complaint'),
    path('electricity_complaint/',views.electricity_complaint,name='electricity_complaint'),
    path('drain_complaint/',views.drain_complaint,name='drain_complaint'),
    path('road_complaint/',views.road_complaint,name='road_complaint'),
    path('park_complaint/',views.park_complaint,name='park_complaint'),
    path('update/<str:pk>/<int:ids>/',views.update,name='update'),
    path('water_update/<str:pk>/<int:ids>/',views.water_update,name='water_update'),
    path('electricity_update/<str:pk>/<int:ids>/',views.electricity_update,name='electricity_update'),
    path('drain_update/<str:pk>/<int:ids>/',views.drain_update,name='drain_update'),
    path('road_update/<str:pk>/<int:ids>/',views.road_update,name='road_update'),
    path('park_update/<str:pk>/<int:ids>/',views.park_update,name='park_update'),
    path('pending_complaint/',views.pending_complaint,name='pending_complaint'),
    path('feedback/',views.feedback,name='feedback'),
    path('verify_email/',views.verify_email,name='verify_email'),
    path('water_complaint/password_change_water/',views.password_change_water,name='password_change_water'),
    path('password_change_elec/',views.password_change_elec,name='password_change_elec'),
    path('password_change_drain/',views.password_change_drain,name='password_change_drain'),
    path('password_change_road/',views.password_change_road,name='password_change_road'),
    path('password_change_park/',views.password_change_park,name='password_change_park'),
    path('password_change_user/',views.password_change_user,name='password_change_user'),
]